### ISSUE TITLE
Max label length is 63 characters

### ISSUE THREAD

**Issue by rbeede** [ypcrts/fqdn#4]
https://github.com/guyhughes/fqdn/blob/1ad687d6cd1d74c5781f673194a744ff105e345c/fqdn/__init__.py#L26-L28

RFC1035 specifies that 63 octets are available besides the 64th octet used for length.  A length octet can only have a max value of 0011 1111 == 63.

The regex is limiting a label to 62 characters, but it can be 63 characters.

Take for example this working web site domain name:

http://www.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com/

The second label has a length of 63.

See also https://webmasters.stackexchange.com/questions/16996/maximum-domain-name-length

**Comment by Shados** [comment]
From RFC 1035, emphasis mine:

> Domain names in messages are expressed in terms of a sequence of labels.
> Each _label is represented as a one octet length field followed by that
> number of octets_.  Since every domain name ends with the null label of
> the root, a domain name is terminated by a length byte of zero.  The
> high order two bits of every length octet must be zero, and the
> remaining six bits of the length field limit the _label to 63 octets or
> less_.
> 
> To simplify implementations, the total length of a domain name (i.e.,
> label octets and label length octets) is restricted to 255 octets or
> less.

It specifies the length octet is part of the label, and that the label as a whole is 63 octets or less. Hence, you can pack your length octet + up to 62 characters... according to the spec. That said, obviously the spec is fucking confusing and the rest of the world has disagreed with it -- intentionally or otherwise. 

Hence the _working_ 63-charcter domain name you've presented. Probably best to violate the spec and accept domains that do actually work in the wild.

**Comment by rbeede** [comment]
"Each label is represented as a one octet length field **_followed_** by that
number of octets."

So the maximum value in the length octet is 0011 1111 == 63 octets.   So it is the one octet length field followed by 63 more octets.

Including DNS over the wire transmission:
"Since every Domain Name ends with the null label of the
   root, a Domain Name is terminated by a length byte of zero."

So the last label's length octet field = 0 but it still takes 1 byte (octet) to transmit that 0-length label.


So it isn't a violation of spec to have a 63-character domain name label.    https://www.rfc-editor.org/std/std13.txt   also reinforces this context with "Labels must be 63 characters or less."


I think confusion arises from textual representation versus the over-the-wire transmission encoding.   This thread has some useful discussion on the various RFCs and contexts:

https://www.ietf.org/mail-archive/web/dnsext/current/msg05871.html
