### ISSUE TITLE
TLD must not be all numeric

### ISSUE THREAD

**Issue by Modusmundi** [ypcrts/fqdn#8]
So I understand if you want to say no to this, but-

https://tools.ietf.org/html/rfc3696#section-2

If we read this in the context of FQDNs, TLDs are expected to be not all-numeric.  This might mean that .k12 might become a TLD in the far-off future, but not say .123.  This may be something to test against for validity of FQDNs, and I could have swore in an older version (1.1.0) this was the case; you treated TLDs in this manner.  Was this an intentional change?

**Comment by ypcrts** [comment]
I agree. Thanks for reporting this. 

Previously numbers were not allowed at all. Then there was a change to allow numbers.
